sudo: required
services:
  - docker

before_install:
  - docker build -t robbypelssers/react-test -f ./react/Dockerfile.dev ./react

scripts:
  - docker run -e CI=true robbypelssers/react-test npm run test

after_success:
  - docker build -t robbypelssers/multi-react ./react
  - docker build -t robbypelssers/multi-nginx ./nginx
  - docker build -t robbypelssers/multi-server ./server
  - docker build -t robbypelssers/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push robbypelssers/multi-react
  - docker push robbypelssers/multi-nginx
  - docker push robbypelssers/multi-server
  - docker push robbypelssers/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-926372350997"
  bucket_path: "docker-multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
